### PR TITLE
Add support for aarch64-apple-darwin

### PR DESCRIPTION
**Pull request by vtenfys**
Adds support for `aarch64-apple-darwin` aka Apple Silicon:

- Add libraries to `glsl-to-spirv-builder/build/universal-apple-darwin` taken from [Vulkan SDK 1.2.162.1](https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.2.162.1/mac/vulkansdk-macos-1.2.162.1.dmg)
  - These libraries are universal so support both `x86_64` and `aarch64`
- Remove `x86_64-apple-darwin` directory and match x86_64 and aarch64 macOS to the universal directory
- Update `build.rs` and `Cargo.toml` to support the new architecture

See also: https://github.com/bevyengine/bevy/issues/1360

### CODE REVIEW

**Comment by cart** [comment]
Very interesting. Using universal binaries seems like the right call here, but it looks like we're bumping our binary size by 15mb. Its _possible_ that this will bring our compressed size over our current crates.io size limit (which we have already had them bump for us once).

I think its worth merging this and attempting to publish, but if it fails we'll need to come up with a plan (ex: ask for another crate size boost, sort out direct compilation, split out into another crate, etc).

One small thing: instead of symlinking aarach64-apple-darwin, can we rename the folder to something like universal-apple-darwin, then in build.rs match the `x86_64-apple-darwin` and `aarch64-apple-darwin` targets to that folder? That feels a bit more explicit / self-documenting to me.

**Comment by vtenfys** [comment]
I've updated as requested :)

**Comment by vtenfys** [comment]
> I think its worth merging this and attempting to publish, but if it fails we'll need to come up with a plan (ex: ask for another crate size boost, sort out direct compilation, split out into another crate, etc).

What are your thoughts on the following ideas?

- making the build script download the libs from some other location (eg host them on the Bevy website) rather than bundling them inside the crate
- dropping this crate in favour of only using `shaderc-rs`, and instructing users to download the Vulkan SDK to provide libs for `shaderc` (or having some way of auto-downloading the SDK during build)

**Comment by cart** [comment]
Sorry for the delay!

> making the build script download the libs from some other location (eg host them on the Bevy website) rather than bundling them inside the crate

I'm not a huge fan of this. It creates a situation where servers being down (that aren't crates.io) breaks builds. Its also a trust issue. It would create a situation where the binary a user downloads today is different from the binary the user downloads tomorrow (ex: I make a mistake or the host becomes hostile).

> dropping this crate in favour of only using shaderc-rs, and instructing users to download the Vulkan SDK to provide libs for shaderc (or having some way of auto-downloading the SDK during build)

This unfortunately overcomplicates builds. shaderc-rs has a number of dependencies that might not be there on a user's machine (this is especially true for windows). I want Bevy to work "out of the box" for as many people as possible

I also just realized that #12 is a problem, which provides even more incentive to try to make something like Naga work. I might investigate that first.

**Pull request closed without merging**
